
# This is a basic workflow to help you get started with the Run Jtest action.
name: JtestOnLinuxWithMaven

on:
  # Trigger the workflow on push or pull request events but only for the main branch.
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel.
jobs:
  build:
    name: Analyze project with Jtest using Maven
    
    permissions:
      # required for all workflows
      security-events: write
    
    # Specifies the type of runner that the job will run on.
    runs-on: [self-hosted, Linux]

    # Steps represent a sequence of tasks that will be executed as part of the job.
    steps:
    
    # Checks out your repository under $GITHUB_WORKSPACE, so that your job can access it.
    - name: Checkout repository
      uses: actions/checkout@v3
    
    # Generates the jtest.data.json input file.
    - name: Create input for Jtest
      run: ./mvnw -s /home/parasoft/apps/ci-cd-common/settings.xml clean install jtest:jtest "-Djtest.skip=true" 

    # Runs code analysis with Jtest
    - name: Run Jtest
      id: jtest
      uses: parasoft/run-jtest-action@2.0.0
      with:
        # installDir: '/home/milosz/work/jtest_under_test/jtest'
        # installDir: '/home/vagrant/dev/jtest_under_test/jtest'
        installDir: '/home/parasoft/apps/jtest-under-test'
        #Uses the jtest.data.json generated with the Maven command in the previous step
        input: target/jtest/jtest.data.json
        

    # Uploads analysis results in the SARIF format, so that they are displayed as GitHub code scanning alerts.
    - name: Upload results (SARIF)
      if: always()
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: reports/report.sarif # reports is a default location for reports directory

    # Uploads an archive that includes all report files (.xml, .html, .sarif).
    - name: Archive reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: Static analysis reports
        path: reports/*.*